require "active_support"
require "active_support/core_ext"

require "symbolic_math/version"
require "symbolic_math/exceptions"

require "symbolic_math/function"
require "symbolic_math/functions/registry"
require "symbolic_math/functions/default_registry"
require "symbolic_math/variables/registry"
require "symbolic_math/variables/default_registry"
require "symbolic_math/context"

require "symbolic_math/ast/node"

require "symbolic_math/ast/literal"
require "symbolic_math/ast/number"
require "symbolic_math/ast/string"
require "symbolic_math/ast/boolean"
require "symbolic_math/ast/variable"

require "symbolic_math/ast/parent"
require "symbolic_math/ast/unary_operator"
require "symbolic_math/ast/unary_plus"
require "symbolic_math/ast/unary_minus"
require "symbolic_math/ast/unary_inverse"
require "symbolic_math/ast/unary_bitwise_not"
require "symbolic_math/ast/unary_logical_not"
require "symbolic_math/ast/unary_identity"
require "symbolic_math/ast/operator"
require "symbolic_math/ast/arithmetic_operator"
require "symbolic_math/ast/plus"
require "symbolic_math/ast/times"
require "symbolic_math/ast/exponent"
require "symbolic_math/ast/function"
require "symbolic_math/ast/bitwise_operator"
require "symbolic_math/ast/bitwise_and"
require "symbolic_math/ast/bitwise_or"
require "symbolic_math/ast/bitwise_xor"
require "symbolic_math/ast/logical_operator"
require "symbolic_math/ast/logical_and"
require "symbolic_math/ast/logical_or"
require "symbolic_math/ast/logical_less_than"
require "symbolic_math/ast/logical_greater_than"
require "symbolic_math/ast/logical_less_than_or_equal_to"
require "symbolic_math/ast/logical_greater_than_or_equal_to"
require "symbolic_math/ast/function"
require "symbolic_math/ast/list"
require "symbolic_math/ast/indexing"

require "symbolic_math/ast/builder"

require "symbolic_math/token"
require "symbolic_math/tokens/comma"
require "symbolic_math/tokens/group"
require "symbolic_math/tokens/number"
require "symbolic_math/tokens/operator"
require "symbolic_math/tokens/string"
require "symbolic_math/tokens/arithmetic_operator"
require "symbolic_math/tokens/logical_operator"
require "symbolic_math/tokens/bitwise_operator"
require "symbolic_math/tokens/word"

require "symbolic_math/tokenizer"

require "symbolic_math/parsing/component"

require "symbolic_math/parsing/element"
require "symbolic_math/parsing/number"
require "symbolic_math/parsing/string"
require "symbolic_math/parsing/boolean"
require "symbolic_math/parsing/variable"
require "symbolic_math/parsing/function"
require "symbolic_math/parsing/group"
require "symbolic_math/parsing/round_group"
require "symbolic_math/parsing/square_group"
require "symbolic_math/parsing/list"
require "symbolic_math/parsing/indexing"
require "symbolic_math/parsing/argument"

require "symbolic_math/parsing/unary_operator"
require "symbolic_math/parsing/unary_plus"
require "symbolic_math/parsing/unary_minus"

require "symbolic_math/parsing/operator"
require "symbolic_math/parsing/arithmetic_operator"
require "symbolic_math/parsing/plus"
require "symbolic_math/parsing/minus"
require "symbolic_math/parsing/times"
require "symbolic_math/parsing/divide"
require "symbolic_math/parsing/exponent"
require "symbolic_math/parsing/bitwise_operator"
require "symbolic_math/parsing/bitwise_and"
require "symbolic_math/parsing/bitwise_or"
require "symbolic_math/parsing/bitwise_xor"
require "symbolic_math/parsing/bitwise_not"
require "symbolic_math/parsing/bitwise_not_not"
require "symbolic_math/parsing/logical_operator"
require "symbolic_math/parsing/logical_less_than"
require "symbolic_math/parsing/logical_greater_than"
require "symbolic_math/parsing/logical_less_than_or_equal_to"
require "symbolic_math/parsing/logical_greater_than_or_equal_to"
require "symbolic_math/parsing/logical_and"
require "symbolic_math/parsing/logical_or"
require "symbolic_math/parsing/logical_not"
require "symbolic_math/parsing/logical_not_not"

require "symbolic_math/parser"

require "symbolic_math/calculator"

module SymbolicMath
end
